name: BlogCI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy blog.
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true # Checkout private submodules(themes or something else).

    - name: Install Dependencies
      run: npm install
    
    # Deploy hexo blog website.
    - name: Deploy
      id: deploy
      uses: sma11black/hexo-action@master
      with:
        deploy_key: ${{ secrets.DEPLOY_KEY }}
        user_name: Abingcbc
        user_email: 19990626.love@163.com
        commit_msg: ${{ github.event.head_commit.message }} 
    - name: Set Custom Domain Name
      run: echo blog.abingcbc.cn > CNAME
    - name: Get the output
      run: |
        echo "${{ steps.deploy.outputs.notify }}"