name: BlogCI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: A job to deploy blog.
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true # Checkout private submodules(themes or something else).
    # Deploy hexo blog website.
    - name: Deploy
      id: deploy
      uses: Abingcbc/hexo-deploy-action@master
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        USER_NAME: Abingcbc
        USER_EMAIL: 19990626.love@163.com
        BRANCH: gh-pages
        GIT_REPO: git@github.com:Abingcbc/blog.git